version: '3.8'
services:
  # backend:
  #   build: .
  #   volumes:
  #     - ./backend:/app
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - dev-mysql
  #   environment:
  #     - DB_HOST=dev-mysql
  #     - DB_USER=udemy
  #     - DB_PASSWORD=udemy
  #     - DB_NAME=udemy
  #     - DB_PORT=3306
  #   networks:
  #     - lesson
  dev-mysql:
    image: mysql:8.0
    ports:
      - "3307:3306" 
    environment:
      MYSQL_ROOT_PASSWORD: udemy
      MYSQL_USER: udemy
      MYSQL_PASSWORD: udemy
      MYSQL_DATABASE: udemy
    restart: always
    networks:
      - lesson
networks:
  lesson:
